### ISSUE TITLE
AuthenticatedComponent#checkAuth uses previous props when called from `componentWillReceiveProps`

### ISSUE THREAD

**Issue by vjpr** [joshgeller/react-redux-jwt-auth-example#10]
If the `isAuthenticated` state changes, `checkAuth` is called but uses the previous props. `checkAuth` should accept `props` as a parameter.

**Comment by mjrussell** [comment]
@vjpr I submitted a [PR](#12) which uses a library I wrote for the authentication checks. This issue should be fixed in that PR since the library checks the auth against the `nextProps` in [componentWillReceiveProps](https://github.com/mjrussell/redux-auth-wrapper/blob/master/src/index.js#L58)
