### ISSUE TITLE
why index.js is needed in each folder

### ISSUE THREAD

**Issue by mars76** [joshgeller/react-redux-jwt-auth-example#22]
Hi,

  I am not sure why we need a index.js in each of the folders (actions, routes, views).

  For ex: we have views/HomeView.js and we are doing export default in it.

  Why do we need to explicitly do export HomeView in index.js ??

Thanks

**Comment by joshgeller** [comment]
Hey @mars76, you're right, this project could use a lot of cleanup. I plan to do a full re-write in the coming weeks.
