### ISSUE TITLE
Make reducers pure

### ISSUE THREAD

**Issue by dferber90** [joshgeller/react-redux-jwt-auth-example#3]
Thanks for this awesome example!

I noticed one small detail that could be improved. As far as I understand redux, side effects should be moved to action creators, instead of happening in the reducer. For this reason all modifications to `localStorage` should happen in the action creators (in the `actions` folder) instead of in the reducer.

Is there a reason you decided to do it another way?
Would you accept a PR changing this? Not sure whether I get around to doing it though.

**Comment by joshgeller** [comment]
Great point - I can take care of the updates, thanks for mentioning it!

**Comment by dferber90** [comment]
Awesome :+1:

**Comment by joshgeller** [comment]
Updated with 9e2d95e
