### ISSUE TITLE
Why do you duplicate functionality? Why don't you use Presentational Components?

### ISSUE THREAD

**Issue by wzup** [joshgeller/react-redux-jwt-auth-example#34]
Did you read this? http://redux.js.org/docs/basics/UsageWithReact.html#presentational-and-container-components

It looks like you didn't.

Why do you combine Presentational Component with Container Component? If you do intentionally, could you please elaborate on your decission? Or just tell us you coudn't find any better way to design the auth system.

You have two chained Container Components. And for both of them you call `connect`. And both of them make web requests. Don't you think that they duplicate the same functionality?

`ProtectedView` component is not a view (or presentation component). It is a Container Component.
`requireAuthentication` function returns `AuthenticatedComponent` which is a Container Component as well.

And then you do this. You pass one Container Component to another Container Component and make both of them do web requests:
```
requireAuthentication(ProtectedView)
```

Why?

**Comment by joshgeller** [comment]
Honestly, because I wrote this whole thing in a few hours and never anticipated anyone to see it. I haven't touched it in months, it needs to be completely written, and it's horribly out-of-date.
